name: GameBroadCast
version: '1.0'
main: net.dxzzz.gamebroadcast.GameBroadCast
depend: [PlaceholderAPI]

commands:
  yq:
    description: "游戏广播快速拉人"
    permission: GameBroadCast.Normal

permissions:
  GameBroadCast.Normal:
    default: true